apiVersion: v1
kind: Service
metadata:
  name: multi-doc-chat
  labels:
    app: multi-doc-chat
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: multi-doc-chat
